-- Supabase Backend Setup SQL
-- Execute these scripts in your Supabase project's SQL Editor

-- 1. Create Tables
-- Profiles table linked to authenticated users
CREATE TABLE public.profiles (
  id UUID NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT,
  current_streak INT DEFAULT 0 NOT NULL,
  longest_streak INT DEFAULT 0 NOT NULL,
  last_completed_at TIMESTAMPTZ
);

-- Meditation logs table
CREATE TABLE public.meditation_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  completed_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  video_id TEXT NOT NULL,
  video_title TEXT
);

-- Predefined videos table
CREATE TABLE public.predefined_videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  thumbnail_url TEXT
);

-- 2. Create Server-Side Streak Logic Function
CREATE OR REPLACE FUNCTION handle_meditation_completion(video_id_param TEXT, video_title_param TEXT)
RETURNS TABLE (
  new_streak INT,
  new_longest_streak INT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  profile_data RECORD;
  updated_streak INT;
BEGIN
  -- Get user's current profile data
  SELECT * INTO profile_data
  FROM public.profiles
  WHERE id = auth.uid();

  -- Insert the new log entry
  INSERT INTO public.meditation_logs (user_id, video_id, video_title)
  VALUES (auth.uid(), video_id_param, video_title_param);

  -- Calculate the new streak
  IF profile_data.last_completed_at IS NULL OR profile_data.last_completed_at::date < (NOW() AT TIME ZONE 'utc' - INTERVAL '1 day')::date THEN
    -- If last completion was not yesterday or is null, reset streak to 1
    updated_streak := 1;
  ELSIF profile_data.last_completed_at::date = (NOW() AT TIME ZONE 'utc' - INTERVAL '1 day')::date THEN
    -- If last completion was yesterday, increment streak
    updated_streak := profile_data.current_streak + 1;
  ELSE
    -- If already completed today, streak does not change
    updated_streak := profile_data.current_streak;
  END IF;

  -- Update the profiles table and update longest streak if necessary
  UPDATE public.profiles
  SET
    current_streak = updated_streak,
    longest_streak = GREATEST(profile_data.longest_streak, updated_streak),
    last_completed_at = NOW() AT TIME ZONE 'utc'
  WHERE id = auth.uid();

  RETURN QUERY SELECT updated_streak, GREATEST(profile_data.longest_streak, updated_streak);
END;
$$;

-- 3. Enable Row Level Security (RLS) and Create Policies
-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meditation_logs ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Users can view and manage their own profile." ON public.profiles
  FOR ALL USING (auth.uid() = id);

CREATE POLICY "Users can view and manage their own meditation logs." ON public.meditation_logs
  FOR ALL USING (auth.uid() = user_id);

-- Allow public read access for predefined videos
ALTER TABLE public.predefined_videos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read predefined videos." ON public.predefined_videos
  FOR SELECT USING (true);

-- 4. Seed Predefined Videos
INSERT INTO public.predefined_videos (video_id, title, description, thumbnail_url)
VALUES
  (
    'tybOi4hjZFQ',
    '10-Minute Guided Morning Meditation',
    'Start your day with a calming guided practice focused on mindful breathing.',
    'https://img.youtube.com/vi/tybOi4hjZFQ/hqdefault.jpg'
  ),
  (
    'q9HFoRSTaMA',
    'Evening Wind-Down Meditation',
    'Release stress and prepare for restful sleep with this gentle evening session.',
    'https://img.youtube.com/vi/q9HFoRSTaMA/hqdefault.jpg'
  )
ON CONFLICT (video_id) DO NOTHING;
